export const browserCoreExamples = [
  "clawdbot-cn browser status",
  "clawdbot-cn browser start",
  "clawdbot-cn browser stop",
  "clawdbot-cn browser tabs",
  "clawdbot-cn browser open https://example.com",
  "clawdbot-cn browser focus abcd1234",
  "clawdbot-cn browser close abcd1234",
  "clawdbot-cn browser screenshot",
  "clawdbot-cn browser screenshot --full-page",
  "clawdbot-cn browser screenshot --ref 12",
  "clawdbot-cn browser snapshot",
  "clawdbot-cn browser snapshot --format aria --limit 200",
  "clawdbot-cn browser snapshot --efficient",
  "clawdbot-cn browser snapshot --labels",
];

export const browserActionExamples = [
  "clawdbot-cn browser navigate https://example.com",
  "clawdbot-cn browser resize 1280 720",
  "clawdbot-cn browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "clawdbot-cn browser press Enter",
  "clawdbot-cn browser hover 44",
  "clawdbot-cn browser drag 10 11",
  "clawdbot-cn browser select 9 OptionA OptionB",
  "clawdbot-cn browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawdbot-cn browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "clawdbot-cn browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawdbot-cn browser console --level error",
  "clawdbot-cn browser pdf",
];
