export const browserCoreExamples = [
  "moltbot-cn browser status",
  "moltbot-cn browser start",
  "moltbot-cn browser stop",
  "moltbot-cn browser tabs",
  "moltbot-cn browser open https://example.com",
  "moltbot-cn browser focus abcd1234",
  "moltbot-cn browser close abcd1234",
  "moltbot-cn browser screenshot",
  "moltbot-cn browser screenshot --full-page",
  "moltbot-cn browser screenshot --ref 12",
  "moltbot-cn browser snapshot",
  "moltbot-cn browser snapshot --format aria --limit 200",
  "moltbot-cn browser snapshot --efficient",
  "moltbot-cn browser snapshot --labels",
];

export const browserActionExamples = [
  "moltbot-cn browser navigate https://example.com",
  "moltbot-cn browser resize 1280 720",
  "moltbot-cn browser click 12 --double",
  'moltbot-cn browser type 23 "hello" --submit',
  "moltbot-cn browser press Enter",
  "moltbot-cn browser hover 44",
  "moltbot-cn browser drag 10 11",
  "moltbot-cn browser select 9 OptionA OptionB",
  "moltbot-cn browser upload /tmp/file.pdf",
  'moltbot-cn browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "moltbot-cn browser dialog --accept",
  'moltbot-cn browser wait --text "完成"',
  "moltbot-cn browser evaluate --fn '(el) => el.textContent' --ref 7",
  "moltbot-cn browser console --level error",
  "moltbot-cn browser pdf",
];
